[#7] 회원가입 기능 구현(비밀번호, 이메일 암호화)
f-lab-edu/king-of-settlement pull request #17
Opened 2024-04-29 11:41 UTC by melody-story

## PR 체크리스트
- [x] [커밋 메시지 컨벤션](https://github.com/f-lab-edu/king-of-settlement/wiki/%EC%BB%A8%EB%B2%A4%EC%85%98-%EB%B0%8F-%EB%AC%B8%ED%99%94#commit-message)에 맞게 작성했습니다. 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

## PR 유형
어떤 변경 사항이 있나요?
- [x] feat: 새로운 기능 추가

## 연관된 이슈
- #7 

## 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요.
- 회원가입시 비밀번호와 이메일을 암호화하여 DB에 저장되도록 하였습니다.

## 이 PR은 중대한 변화를 포함하고 있나요?
기존 애플리케이션에 어떠한 영향을 미치는지 설명해주세요.
- [ ] Yes
- [x] No

## 리뷰 요구사항
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
- N/A

2024-04-29 16:48 UTC, f-lab-jd requested changes
고생하셨습니다! 리뷰 드린 내용 한번 확인 부탁드립니다. 
그리고 지난번에 리뷰드렸듯이 SignUpTest, UserTest 는 잘못된 네이밍의 테스트 클래스입니다.
해당 테스트 클래스의 목적을 고려해서 패키지와 네이밍을 다시 고려해주시면 좋을 것 같습니다!

2024-04-29 16:48 UTC, f-lab-jd commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-security")
security 를 의존하신 이유가 있으신가요? 만약 암호화 때문이라면 반드시 security 를 의존해야하는지 한번 확인 부탁드리겠습니다!

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
>  		try {
`BindingResult` 를 사용해서 유효성 검증 후 직접 에러를 확인하고 있는데요. SpringMVC 에서는  `MethodArgumentNotValidException` 을 자동으로 발생시키기 때문에 더 명시적으로 예외를 던지는 경우가 아니라면 불필요해보입니다.  그리고 중복된 에러처리에 대해 `@ExceptionHandler` 를 사용해서 개선해보시면 좋을 것 같습니다.

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/SignUpResponse.java
> +public record SignUpResponse(String message, Long userId) {
`message` 는 왜 필요한가요? RestfulAPI 설계 방식을 고려해서 `message` 가 필요할지 다시 고민해보시면 좋을 것 같습니다. 
반드시 필요하다면 이를 공통화할 수 있지 않을까요?

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		User user;
43번째 라인에 선언 후 리턴문도 해당 블락에 포함시키면 불필요한 선언은 필요 없을 것 같습니다.

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
>  				throw new SignUpException(bindingResult.getFieldError().getDefaultMessage());
`getDefaultMessage` 메소드는 NullPointerException  을 발생시키지 않을까요?

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/UserProfile.java
> +@Embeddable
해당 어노테이션에 대한 설명이 누락되어있습니다. 추가로 왜 사용하셨는지도 댓글로 설명해주시면 감사하겠습니다!

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/SignUpResponse.java
> +public record SignUpResponse(String message, Long userId) {
그리고 `record` 클래스를 선언하는 기준은 무엇인가요~?

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/AESEncryption.java
> +			throw new EncryptException("복호화중 에러가 발생했습니다.");
복호화 에러라면 `DecryptException` 이 더 명확하지 않을까요?

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/AESEncryption.java
> +	public static String encrypt(String text) throws EncryptException {
멘토링 시간에 encrypt 와 decypt 메소드에 대해 한번 설명해주시면 좋을 것 같습니다~!

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		if (userRepository.findOneByEmail(email) != null) {
`Optional` 의 기능과 제공하는 메소드에 대해 다시 한번 공부해보시면 좋을 것 같습니다.

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		String hashedPassword = passwordEncoder.encode(req.getPassword());
encrypted 와 hashed 의 의미상 차이가 무엇인가요? 네이밍만 보았을때 두 변수가 어떤 차이가 있는지 모르겠습니다.

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		PasswordEncoder passwordEncoder = Pbkdf2PasswordEncoder.defaultsForSpringSecurity_v5_8();
요 라인은 어떤 역할을 하나요?!

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		User user = User.inActiveStatusOf(encryptedEmail, hashedPassword);
`inActiveStatusOf` 라는 메소드의 네이밍을 보았을때, 어떤 역할일지 감이 잘 오지 않습니다. 
팩토리 메소드를 사용하는게 목적이셨다면, 어떤 네이밍이 적합할지 다시한번 고민해보시면 좋을 것 같습니다!

2024-04-29 16:48 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
>  		return userRepository.save(user);
email 과 password 이외의 값은 회원가입할때 저장을 하지 않아도 되나요?!

2024-05-09 07:01 UTC, melody-story commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-security")
security를 의존하지 않고도 암호화 할수있습니다! 해당 의존성은 아껴두었다가 나중에 사용하도록 하고 일반적인 방법으로 암호화구현해보겠습니다:)

2024-05-09 09:00 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/SignUpResponse.java
> +public record SignUpResponse(String message, Long userId) {
프로젝트 내 record 적용 기준을 아래와 같이 정해보았습니다.
-자동생성 메서드 외에 추가 메소드 정의 필요없는 간단한 DTO 생성시
-최초 생성 후 값이 변경되면 안되는 객체 생성시

2024-05-09 09:12 UTC, melody-story commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-security")
커밋을 나누어 2가지 방법으로 비밀번호 단방향 암호화를 구현해보았습니다.
1. SHA-256+ salt
2. Bcrypt

2024-05-09 09:45 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/AESEncryption.java
> +			throw new EncryptException("복호화중 에러가 발생했습니다.");
아 수정해서 적용하였습니다!

2024-05-09 09:46 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		User user;
리턴문 try 블록 내에 넣어 수정하였습니다!

2024-05-09 09:57 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/SignUpResponse.java
> +public record SignUpResponse(String message, Long userId) {
201(created)  http 상태코드는 회원가입 성공케이스 단 한가지로 의미전달을 명확히할 수 있으나, 400(bad request)은 어떤 원인에 의한 요청실패인지 클라이언트에게 해당 메시지를 전달해주기 위한 용도로 message를 삽입하였습니다. 공통화하여 전달하는 방식으로 개선해보겠습니다.:)

2024-05-09 11:29 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
>  		try {
먼저 공통응답 DTO를 생성하면서, 유효성 검증 에러메시지가 응답되도록 코드를 개선하였습니다.
예외처리관련 부분은 이전에 PR을 따로 생성하여 반영하였습니다.
@ExceptionHandler 적용 코드는 [이곳](https://github.com/f-lab-edu/king-of-settlement/pull/21)에서 리뷰 부탁드립니다!

2024-05-09 11:57 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
>  				throw new SignUpException(bindingResult.getFieldError().getDefaultMessage());
Optional 적용하여 수정해보았습니다.

2024-05-09 12:14 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
>  		return userRepository.save(user);
회원가입 후 최초 로그인시 닉네임을 포함한 프로필정보를 설정하도록 합니다.

2024-05-09 12:15 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		String hashedPassword = passwordEncoder.encode(req.getPassword());
encrypted~로 통일하였습니다!

2024-05-09 12:15 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		if (userRepository.findOneByEmail(email) != null) {
해당 부분 개선해보았습니다.

2024-05-09 12:17 UTC, melody-story commented
테스트 코드 네이밍은 [이전 PR](https://github.com/f-lab-edu/king-of-settlement/pull/3)에서 수정하였습니다!

2024-05-09 12:25 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/UserProfile.java
> +@Embeddable
이메일, 비밀번호와 다르게 수정가능한 회원정보인 닉네임, 소개, 이미지는 프로필 정보에 해당하는 부분으로 그 성질이 달라 구분하기 위해 분리하였습니다.

2024-05-09 12:43 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		User user = User.inActiveStatusOf(encryptedEmail, hashedPassword);
of로 수정해보았습니다.

2024-05-09 12:45 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		PasswordEncoder passwordEncoder = Pbkdf2PasswordEncoder.defaultsForSpringSecurity_v5_8();
spring security 의존성으로부터 Pbkdf2 암호화알고리즘을 사용한 password인코딩 객체를 가져오는 코드입니다.

2024-05-09 12:46 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/AESEncryption.java
> +	public static String encrypt(String text) throws EncryptException {
알겠습니다~!

2024-07-20 08:14 UTC, f-lab-jd approved these changes
👍

2024-07-28 14:51 UTC, closed without merging