[#8] 로그인 기능 구현
f-lab-edu/king-of-settlement pull request #18
Opened 2024-04-29 12:40 UTC by melody-story

## PR 체크리스트
- [x] [커밋 메시지 컨벤션](https://github.com/f-lab-edu/king-of-settlement/wiki/%EC%BB%A8%EB%B2%A4%EC%85%98-%EB%B0%8F-%EB%AC%B8%ED%99%94#commit-message)에 맞게 작성했습니다. 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

## PR 유형
어떤 변경 사항이 있나요?
- [x] feat: 새로운 기능 추가

## 연관된 이슈
- #8 

## 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요.
- [x] 세션기반 로그인 기능을 추가하였습니다.
  - 사용자 로그인시 서버에서 세션을 발급하여 DB에 저장하고, 클라이언트에 전달합니다.
  - 클라이언트는 세션아이디를 가진 쿠키를 포함하여 서버에 요청을 합니다.
  - 세션아이디를 DB에서 조회하여 유효한 세션아이디인지 확인 및 사용자를 식별, 조회 후 응답합니다.

## 이 PR은 중대한 변화를 포함하고 있나요?
기존 애플리케이션에 어떠한 영향을 미치는지 설명해주세요.
- [x] No

## 리뷰 요구사항
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
- N/A

2024-04-29 17:03 UTC, f-lab-jd requested changes
고생하셨습니다! 리뷰드린 내용 한번 확인 부탁드리겠습니다~~

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	public void updateSessionId(String sessionId) {
소스코드 전체에 `sessionId`, `sessionKey` 둘 중 하나로 네이밍 통일이 필요합니다.

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/UserProfile.java
> +@ToString
`ToString` 에 대해 설명이 누락되어있습니다. 해당 어노테이션이 필요한 이유가 무엇인가요?

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		User loginUser;
이전 PR 에서 남겼던 리뷰 내용과 동일한 내용입니다!

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/LogInRequest.java
> +	public LogInRequest() {
기본 생성자가 필요한 이유는 무엇인가요?

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/LogInRequest.java
> +	public LogInRequest(String email, String password) {
마찬가지로 불필요한 생성자 아닌가요?

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	public String getEmail() {
`getDecrypedEmail` 이 더 명확한 네이밍일 것 같습니다!

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		session.setMaxInactiveInterval(1800);
매직 넘버는 상수로 빼는게 좋습니다. 
그리고 setMaxInactiveInterval 를 설정하시는 이유가 무엇인가요? 
현재 세션은 DB 에 저장되는 방식으로 구현하신 것 아닌가요?!

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/SessionConst.java
> +public class SessionConst {
사용하지 않는 클래스와 변수인데 목적이 무엇인가요?

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
>  	public User signUp(SignUpRequest req) throws EncryptException, SignUpException {
java 에서는 약어보다는 풀네임을 선호합니다.

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +	public User login(HttpServletRequest request, LogInRequest req) throws UserDoseNotExist {
java 에서는 약어보다는 풀네임을 선호합니다. 프로젝트 전반적으로 일관성있게 수정해주시면 좋을 것 같습니다.

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +	public User login(HttpServletRequest request, LogInRequest req) throws UserDoseNotExist {
`UserDoseNotExist` 은 RuntimeException 인데 `throws` 에 포함시킨 이유가 무엇인가요?

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/exception/UserDoseNotExist.java
> +public class UserDoseNotExist extends RuntimeException {
Exception  클래스는 뒤에 Exception 이라는 postfix 를 붙여주는게 명확합니다.

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/exception/UserDoseNotExist.java
> +public class UserDoseNotExist extends RuntimeException {
그리고 `Does` 부분에 오타가 있습니다!

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		return ResponseEntity.status(HttpStatus.ACCEPTED).body(new SignUpResponse("LogIn Succeed!", loginUser.getId()));
userId 이외의 값도 필요하지 않을까요?

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		User existUser = userRepository.findOneByEmail(AESEncryption.encrypt(email))
변수명은 명사형으로 짓는게 좋습니다.

2024-04-29 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		if (passwordEncoder.matches(password, existUser.getPassword())) {
패스워드 매치가 틀린 경우에는 예외를 던져야하지 않을까요?

2024-04-29 17:04 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		return ResponseEntity.status(HttpStatus.ACCEPTED).body(new SignUpResponse("LogIn Succeed!", loginUser.getId()));
`ACCEPTED` 로 설정하신 이유가 있으신가요~?

2024-05-10 02:48 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/exception/UserDoseNotExist.java
> +public class UserDoseNotExist extends RuntimeException {
수정하였습니다!

2024-05-10 08:28 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		return ResponseEntity.status(HttpStatus.ACCEPTED).body(new SignUpResponse("LogIn Succeed!", loginUser.getId()));
앗 의미를 잘못알아 상태코드를 잘못 적용하였습니다. 202 코드는 요청이 수신되었고, 아직 작업이 수행중이라는 상태코드로 해당 API에는 해당되지 않아, 요청된 작업이 성공적으로 수행되었음을 나타내는 200으로 변경하였습니다.

2024-05-10 08:44 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/LogInRequest.java
> +	public LogInRequest() {
사용하지 않는 생성자 삭제 하였습니다..!!

2024-05-10 08:45 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		User loginUser;
이전 PR에서 signUp 메소드관련 부분 참고해서 수정하였습니다.

2024-05-13 11:26 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/LogInRequest.java
> +	public LogInRequest(String email, String password) {
사용하지 않는 생성자 삭제 하였습니다..!!

2024-05-13 11:38 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	public void updateSessionId(String sessionId) {
통일하였습니다.

2024-05-13 11:57 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/UserProfile.java
> +@ToString
어노테이션 설명추가하였습니다.
디버깅시 로그에서 요청 또는 응답시 프로필 값을 확인하기 위한 용도로 추가하였습니다.

2024-05-13 12:45 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	public String getEmail() {
네 수정하였습니다!

2024-05-13 12:46 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
>  	public User signUp(SignUpRequest req) throws EncryptException, SignUpException {
수정하였습니다.

2024-05-13 13:09 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		if (passwordEncoder.matches(password, existUser.getPassword())) {
예외 추가하였습니다!

2024-05-13 13:13 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/UserService.java
> +		User existUser = userRepository.findOneByEmail(AESEncryption.encrypt(email))
수정하였습니다.

2024-05-13 13:13 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +		return ResponseEntity.status(HttpStatus.ACCEPTED).body(new SignUpResponse("LogIn Succeed!", loginUser.getId()));
이외 사용자 정보들도 응답시 추가하였습니다.:)

2024-07-20 08:14 UTC, f-lab-jd approved these changes
👍

2024-08-03 06:47 UTC, merged