[#20] 예외 처리 개선
f-lab-edu/king-of-settlement pull request #21
Opened 2024-05-07 06:59 UTC by melody-story

## PR 체크리스트
- [x] [커밋 메시지 컨벤션](https://github.com/f-lab-edu/king-of-settlement/wiki/%EC%BB%A8%EB%B2%A4%EC%85%98-%EB%B0%8F-역%EB%AC%B8%ED%99%94#commit-message)에 맞게 작성했습니다. 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

## PR 유형
어떤 변경 사항이 있나요?
- [x] feat: 새로운 기능 추가

## 연관된 이슈선
- #20

## 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요.
- exception handler 적용 
- controller advice 적용 
- controller return 타입 변경 
- api 요청시 response body 데이터 구조 변경

2024-05-13 17:03 UTC, f-lab-jd requested changes
고생하셨습니다. 리뷰드린 내용 한번 확인 부탁드리고, 주석 관련해서는 중복 제거해주심 좋을 것 같습니다.

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/error/CommonStatusCode.java
> +	private final Integer statusCode;
httpStatusCode 와 statusCode 를 분리하신 이유가 있으신가요?

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/CommonResponse.java
> +	public static <T> CommonResponse<T> success(T data, Result result) {
이렇게 여러가지로 오버로딩하신 이유가 있으신가요? 
오히려 복잡도가 더 늘어나거나, 유지보수에 불편함이 생기지는 않을까요? 
실제로 사용하는 메소드만 선언해주시면 좋을 것 같습니다.

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/error/CommonStatusCode.java
> +	METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED.value(), 9500, "method not allowed.");
description 필드에 대해 한글/영어 일관성있게 처리해주시면 더 좋을 것 같습니다.

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/error/UserStatusCode.java
> +	USER_CREATED(HttpStatus.CREATED.value(), 1000, "유저가 생성되었습니다."),
CommonStatusCode 에서 많은 StatusCode 를 정의해주셨는데요. 앞으로 User  를 비롯해서 도메인마다 StatusCode가 생기는 구조일까요?  StatusCode 를 이렇게 세분화했을때 장/단점이 무엇이 있을까요?

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/exception/ApiException.java
> +public class ApiException extends RuntimeException implements ApiExceptionInterface {
CommonResponse 와 같은 리뷰입니다.

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/error/CommonStatusCode.java
> +// Lombok 라이브러리에서 제공하는 기능 중 하나로, 클래스의 필드에 대한 Getter 메소드를 자동으로 생성한다.
최초에 정했던 것 처럼 어노테이션에 대한 주석은 "최초 등장한 경우" 적어주시면 좋을 것 같습니다.

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +			throw new UserException(CommonStatusCode.INVALID_INPUT_VALUE, bindingResult.getFieldError().getDefaultMessage());
이 부분이 매 API 마다 중복이 될텐데, 공통화 할 수 있는 방법은 없을까요?

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +	public ResponseEntity<CommonResponse<?>> signUp(
`?`로 바꾸신 이유가 무엇인가요~?

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
GlobalExceptionHandler 와 ApiExceptionHandler 를 구분하신 이유가 있으신가요?

2024-05-13 17:03 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/exception/handler/GlobalExceptionHandler.java
> +		return ResponseEntity.status(500).body(CommonResponse.fail(CommonStatusCode.SERVER_ERROR, exception));
HttpStatus enum 을 사용하면 불필요한 상수선언은 줄일 수 있을 것 같습니다.

2024-08-03 11:25 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/CommonResponse.java
> +	public static <T> CommonResponse<T> success(T data, Result result) {
코드의 복잡도 최소화 위해 사용하지 않는 메소드 정리하였습니다~!

2024-08-03 11:33 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/error/CommonStatusCode.java
> +// Lombok 라이브러리에서 제공하는 기능 중 하나로, 클래스의 필드에 대한 Getter 메소드를 자동으로 생성한다.
네 수정하였습니다~!

2024-08-03 11:41 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/error/CommonStatusCode.java
> +	METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED.value(), 9500, "method not allowed.");
네 영어로 통일하겠습니다.

2024-08-03 14:56 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/exception/handler/GlobalExceptionHandler.java
> +		return ResponseEntity.status(500).body(CommonResponse.fail(CommonStatusCode.SERVER_ERROR, exception));
수정하였습니다.

2024-08-03 14:56 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +			throw new UserException(CommonStatusCode.INVALID_INPUT_VALUE, bindingResult.getFieldError().getDefaultMessage());
globalExceptionHandler에서 공통으로 처리되도록 수정해보았습니다.

2024-08-03 15:04 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/error/UserStatusCode.java
> +	USER_CREATED(HttpStatus.CREATED.value(), 1000, "유저가 생성되었습니다."),
네 도메인별로 필요시 예외상태 코드가 생길 예정입니다~!
도메인별로 상태코드를 생성하면 상태코드에 해당하는 오류 상황을 명확하게 표현할 수 있어, 개발자가 오류를 쉽게 파악하고 대처할 수 있습니다.
다만, 상태 코드가 너무 많아서 기억하기 어려울 수 있으며, 실수로 상태 코드가 원래 의미와 다르게 사용될 경우 오류를 찾기 힘들 수 있습니다.

2024-08-03 15:04 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/exception/ApiException.java
> +public class ApiException extends RuntimeException implements ApiExceptionInterface {
반영하였습니다:)

2024-08-03 15:05 UTC, melody-story commented on src/main/java/son/kingofsettlement/common/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
ApiExceptionHandler 사용하지 않아 제거하였습니다.

2024-08-03 15:14 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/UserController.java
> +	public ResponseEntity<CommonResponse<?>> signUp(
모든 유형의 매개변수를 허용하기 위해 와일드카드를 사용하였습니다.

2024-08-04 11:30 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/common/exception/handler/ApiExceptionHandler.java
> +		log.error(">>>>>>> UserException", userException);
실제로 남는 로그 내용은 어떠한가요? 오류의 내용과 오류의 원인을 파악할 수 있을까요?

2024-08-28 14:41 UTC, merged