[#6] 회원가입 기능 구현
f-lab-edu/king-of-settlement pull request #3
Opened 2024-04-03 12:11 UTC by melody-story

## PR 체크리스트
- [x] [커밋 메시지 컨벤션](https://github.com/f-lab-edu/king-of-settlement/wiki/%EC%BB%A8%EB%B2%A4%EC%85%98-%EB%B0%8F-%EB%AC%B8%ED%99%94#commit-message)에 맞게 작성했습니다. 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

## PR 유형
어떤 변경 사항이 있나요?
- [x] feat: 새로운 기능 추가

## 연관된 이슈
- #6 

## 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요.
- 회원가입
  - 이메일 중복 여부확인
  - 회원생성

+ 코드리뷰 반영
- [x] 예외발생시 응답코드가 controller, exception 코드 두가지 방법으로 처리 되어있음. 일관성있게 한가지 방법으로 통일  
- [x] ExceptionHandler, ControllerAdvice 적용 -> #21  
- [x] 어노테이션 주석 멀티 주석으로 수정
- [x] 컨트롤러 메서드네이밍 의미있게 수정하기  
- [x] 컬럼이 없는 필드는 하이버네이트가 자동으로 매핑을 해주지만 실수가 있을 수 있기 때문에 컬럼 어노테이션 적용해주기  
- [x] user 객체 생성 정적메소드팩토리패턴 반영
- [x] 테이블 필드명 user_id-> id user 테이블의 pK가 id이므로 혼선을 줄수는 없으나, FK로 사용될 경우는 user_id로 명명하는 것이 좋음. 
- [x] id라는 postfix 는 테이블의 키를 나타내는데 사용된다. 이때문에 session_id 필드는 FK로 오인될 수 있으므로, session_key로 권장  
- [x] 모든 클래스가 생성자가 필요하지 않다. jpa에서는 기본생서자가 필요한 경우가 있다.
- [x] 커스텀 예외 클래스 `SignUpException`: 미사용 기본생성자생성 어노테이션 제거
- [x] record를 쓰는 기준 명확히 하기
- [x] 단위테스트와 통합테스트의 차이알고 적용하기
- [x] 단순 테스트를 위한 테스트 코드는 제거  
- [x] 테스트 코드 컨벤션 적용(main 과 동일한 패키지 구조)

2024-04-04 15:35 UTC, f-lab-jd requested changes
고생하셨습니다! 리뷰드린내용 한번 꼼꼼히 확인 부탁드리겠습니다~

2024-04-04 15:35 UTC, f-lab-jd commented on build.gradle.kts
> +    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
각 라이브러리를 왜 의존하셨는지 답변해주실 수 있으신가요~? 
혹시 Spring Boot 의 `Dependency Versions` 기능에 대해 아시나요?!

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/SignUpException.java
> +public class SignUpException extends RuntimeException {
Exception 과 ResponseStatus 를 1:1 로 매칭하신 이유는 무엇인가요? 어떤 장단점이 있을까요? 
추가로 `RuntimeException`  을 상속 받는 이유는 무엇인가요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/KingOfSettlementApplication.java
> +// Spring Boot 애플리케이션의 주 클래스에 붙이며, 구성(Configuration), 자동 구성(Auto-configuration), 컴포넌트 스캔을 단순하게 처리해준다. 이를 통해 애플리케이션의 설정과 시작을 편리해짐.
어노테이션 위에 주석으로 설명해주시면 좋을 것 같습니다.
그리고 주석이 길어지는 경우 개행 부탁드리겠습니다!

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/KingOfSettlementApplication.java
> +
https://github.com/f-lab-edu/king-of-settlement/wiki/%EC%BB%A8%EB%B2%A4%EC%85%98-%EB%B0%8F-%EB%AC%B8%ED%99%94#java-coding-style

코딩스타일이 적용된것이죠~?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +@RequiredArgsConstructor
어노테이션에 대한 설명이 빠졌습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +@RequestMapping("/api")
앞에 api를 붙이는 이유가 있으신가요~?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +	@PostMapping("/signup")
RestfulAPI 가 무엇인지에 대해 공부해보시고, 이에 맞게 API 를 설계해주시면 좋을 것 같습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +	public SignUpResponse post(@RequestBody SignUpRequest req) throws Exception {
뒤에 `throws Exception` 을 선언하신 이유는 무엇인가요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/SignUpRequest.java
> +			nicknameValidate(nickname);
메소드는 동사형으로 이름짓는게 좋습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +		return signUpService.join(new User(req.email(), req.password(), req.nickname()));
DTO 를 Service 에 넘기는것은 어떨까요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/SignUpRequest.java
> +		} catch (Exception e) {
`Exception` 을 통째로 catch 하신 이유가 있으신가요? 
지양해야하는 코딩 스타일 중 하나인데요. 어떤 이유 때문인지 한번 고민해보시면 좋을 것 같습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/SignUpRequest.java
> +		if (!email.matches("[a-z_\\-.A-Z0-9]+@[a-z_\\-A-Z]+.[a-z_\\-A-Z]+")) {
Spring Boot 에서 제공하는 Validation기능을 사용하는 것은 어떨까요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/dto/SignUpResponse.java
> +public record SignUpResponse(String message) {
아직 작성중이라고 생각하면 될까요?! 
마찬가지로 RestfulAPI 에 대해 공부해보시고 어떤 응답이 적당할지 적용부탁드립니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +@Table(name = "users")
마찬가로 어노테이션에 대한 설명이 필요합니다. (전반적으로 점검해주심 좋을 것같습니다)
그리고 테이블명은 멘토링때 리뷰드렸던 내용을 반영해주심 좋을 것 같습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	String userEmail;
접근제어자를 사용하지 않으신 이유가 있으신가요? 
접근제어자를 사용하지 않았을때 어떤일이 벌어질까요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	String sessionId;
sessionId 는 어떤값이 저장되나요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +public class User {
`@Column` 이 없는 필드는 어떤 용도인가요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	LocalDateTime updatedDttm;
Java 프로그래밍에서 약어는 지양하는게 좋습니다. `Dttm` 보다는 `At` 이 더 적당해보입니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	}
빈 생성자는 왜 필요할까요~?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	public User(String userEmail, String password, String userNickname) {
https://github.com/f-lab-edu/king-of-settlement/pull/3/files#diff-638ce5b1a47acc094a0a1a00f43f754e3b2e8a58e17ac7f3d79fb0eb6cbc5835R36 와 마찬가지로 실제 비즈니스 로직에 사용하지 않는데 해당 생성자를 만드신 이유가 궁금합니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	String userActivityStatus;
Enum 을 사용하지 않으신 이유가 있으신가요? 
그리고 필드명 앞에 `user` 는 대부분 중복되는데 제거하는것은 어떨까요?

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/SignUpService.java
> +	public SignUpResponse join(User user) {
`SignUp`Service 에서 `join` 이라는 메소드보다는 signUp 을 수행하는게 맞지 않을까요? 
불필요한 네이밍을 혼용해서 사용하는 케이스인 것 같습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/SignUpService.java
> +		// 2.이메일 중복 여부확인
복잡한 로직이 아니라면 주석은 지양하는게 좋습니다. 
최대한 코드를 가독성 있게 작성해서 이해할 수 있도록하는게 좋습니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/main/java/son/kingofsettlement/user/service/SignUpService.java
> +		if (hasDuplicateUser(user.getUserEmail())) {
`has` 보다는 `is` 가 맞는 것 같습니다. 
그리고 `Duplicated` 가 더 적절해보입니다.

2024-04-04 15:35 UTC, f-lab-jd commented on src/test/java/son/kingofsettlement/user/SingUpTest.java
> +class SignUpTest {
테스트코드의 경우 보통 어떤 네이밍 컨벤션으로 사용하는지 찾아보시고 다시 적용해주시면 좋을 것 같습니다.

2024-04-06 08:53 UTC, melody-story commented on src/main/java/son/kingofsettlement/KingOfSettlementApplication.java
> +
네 코드스타일 적용되어진 것입니다:) 주석 다시 수정해서 반영하겠습니다!

2024-04-06 11:59 UTC, melody-story commented on src/main/java/son/kingofsettlement/KingOfSettlementApplication.java
> +// Spring Boot 애플리케이션의 주 클래스에 붙이며, 구성(Configuration), 자동 구성(Auto-configuration), 컴포넌트 스캔을 단순하게 처리해준다. 이를 통해 애플리케이션의 설정과 시작을 편리해짐.
수정하였습니다. [8a6895e](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/8a6895e4c07ea93a620c8e8b2e189546372422ae)

2024-04-06 12:58 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/SignUpService.java
> +		if (hasDuplicateUser(user.getUserEmail())) {
메소드 이름 수정하였습니다. [97adaf9](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/97adaf9438244a4c5de64e016dd01a5b104ef5e7)

2024-04-06 13:00 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/SignUpService.java
> +		// 2.이메일 중복 여부확인
코드 가독성을 위해 주석 삭제하였습니다. [99fa279](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/99fa279245b48cb0b2d2e398ce93aa155c0ab014)

2024-04-06 13:12 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/service/SignUpService.java
> +	public SignUpResponse join(User user) {
불필요하게 혼용된 네이밍 통일하였습니다~! [e51d9d7](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/e51d9d7b483313d70191d7d08681d670aa5f217a)

2024-04-06 13:44 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	public User(String userEmail, String password, String userNickname) {
매개변수가 1개자리인 생성자를 테스트 코드 작성시 간단히 테스트 하기위한 용도로 작성하였습니다. 
현재는 불필요한 코드이므로 삭제하고, 테스트 코드도 수정사항 반영하겠습니다.

[e9b9128](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/e9b9128d37a72b0f4b679d361e1861ec07e9d74d)

2024-04-06 13:47 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	LocalDateTime updatedDttm;
인스턴스 변수 약어 수정하였습니다.
[c75bb2f](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/c75bb2f11ae8dbd1be7aa7d882e36563aa5b644e)

2024-04-06 14:01 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	String userEmail;
dto로 오인하여 접근제어자 private를 붙이는 것을 실수하였습니다..ㅠ 
entity는 테이블과 매핑되어 데이터의 저장, 조회, 수정, 삭제의 작업이 수행됩니다. 
따라서, 한번 생성된 객체의 상태(변수)가 변할수 있는 가능성을 열어두어서는 안됩니다.
이를 위해 해당 클래스 내에 서만 접근가능하도록 하는 `private` 접근제어자를 지정하여, 클래스 외부에서 객체의 상태를 변경하는 일이 없도록 해야합니다. [077a026](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/077a0262551be6949de12236d20c559ae087a310)

2024-04-08 02:29 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +@RequestMapping("/api")
api 엔드포인트와 웹페이지 경로와 구분하기 위해 api를 붙였습니다. 
그러나 이렇게 모든 엔드포인트에 api를 강제 부여하게되면, 데이터 자원이 아닌 명사 api가 추가되어,  명사기반으로 데이터 자원을 식별하는 restfulAPI 설계 원칙에 위배가 됩니다. 
restfulAPI 설계 원칙에 맞게 엔드포인트를 설계하여 수정토록 하겠습니다.

2024-04-08 04:54 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +	@PostMapping("/signup")
네 알겠습니다.:)

2024-04-08 07:15 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +public class User {
필드에 @Column(name="지정이름")을 사용하면, DB table에서 지정한 이름으로 컬럼이름을 생성가능합니다.
위 속성이 지정되지 않은 필드는 본래 이름 대로 DB 테이블의 컬럼과 매핑이 됩니다.
위 두상황 모두  hibernate에 의해 기본적으로 카멜케이스였던 필드가 컬럼에서는 스네이크케이스로 변환됩니다.

2024-04-08 07:26 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	String userActivityStatus;
Enum을 생성자에 사용하였으나, 잘못된 사용방법이라는 것을 깨달았습니다^^;;
Enum 타입그대로를 가져오는 것으로 수정하였습니다.
필드앞에 중복되는 user 제거하였습니다!
[5bff69d](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/5bff69d9396f72f8cc4ea0076bbec8074ace46c8)

2024-04-08 07:44 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	}
빈생성자는 기본생성자라고 불립니다. 자바에서 객체를 생성할 때는 기본 생성자를 통해 생성합니다. 
일반적으로 기본생성자를 작성하지 않아도, 컴파일러에서 컴파일시 기본생성자를 자동으로 생성해주지만, 해당 코드처럼 매개변수가 있는 생성자가 선언된 경우에는 자동으로 생성되지 않으므로 기본생성자를 추가로 작성해주어야 합니다.

따라서, jpa가 엔티티 객체를 생성할 수 있게 해당 코드에 기본생성자를 작성해주어야 합니다.

2024-04-08 08:38 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +@Table(name = "users")
테이블명 리뷰내영 반영 완료하였습니다. [e47eeb1](https://github.com/f-lab-edu/king-of-settlement/pull/3/commits/e47eeb144b05ec8ac4d09f983beb1eaa1de801e8)

2024-04-09 07:40 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +	public SignUpResponse post(@RequestBody SignUpRequest req) throws Exception {
service에서 발생한 예외를 잡기 위해 작성하였는데, 서비스를 수정하는 과정에서 dto만 return하는 코드로 수정되었습니다.
service에서 예외를 던지도록 다시 수정하였습니다.

2024-04-09 10:00 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +		return signUpService.join(new User(req.email(), req.password(), req.nickname()));
service에 requestDTO를 넘기는 것이 보다 깔끔해보여 수정하였습니다~!

2024-04-09 13:56 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/SignUpRequest.java
> +			nicknameValidate(nickname);
수정하였습니다.

2024-04-09 13:57 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/SignUpRequest.java
> +		if (!email.matches("[a-z_\\-.A-Z0-9]+@[a-z_\\-A-Z]+.[a-z_\\-A-Z]+")) {
email 검증부분에 적용해보았습니다:)

2024-04-09 14:12 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/SignUpRequest.java
> +		} catch (Exception e) {
예외를 통째로 catch 하게되면 어느부분에서 어떠한 원인으로 예외가 발생했는지 명확히 알기 어려워 문제 해결시 어려움을 겪게 됩니다.

2024-04-09 14:30 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/SignUpException.java
> +public class SignUpException extends RuntimeException {
일반적으로 예외가 발생하면 HTTP 응답 코드가 500(Internal Server Error)로 설정됩니다.
회원가입 로직에서는 클라이언트가 잘못된 회원 정보로 회원가입을 요청할 시 예외가 발생하도록 되어있습니다.
이때, 클라이언트에게 회원가입에 실패한 원인을 명시적으로 알리기 위해, 예외가 발생되었을 때  500이 아닌 400(Bad Request)을 반환하기 위하여 Exception 과 ResponseStatus 를 1:1 로 매칭하였습니다.

장점:
1. 예외 발생 시 클라이언트는 HTTP 응답 코드를 통해 발생한 문제를 더 잘 파악할 수 있습니다.
2. 각 예외 클래스가 어떤 응답 코드를 반환하는지 명시적으로 알 수 있습니다.

단점:
1. 예외가 발생할 때마다 새로운 예외 클래스를 생성하여 @ResponseStatus 어노테이션을 추가해야 하므로 코드가 복잡해질 수 있습니다.

2024-04-09 14:40 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/SignUpException.java
> +public class SignUpException extends RuntimeException {
`SignUpException`가 `RuntimeException` 을 상속 받는 이유는 컴파일시점이 아닌, 런타임 단계에서 예외를 발생시키기 위함입니다.

2024-04-09 15:16 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/dto/SignUpResponse.java
> +public record SignUpResponse(String message) {
RESTfulAPI의 응답 구조화 위해 ResponseEntity 적용해 보았습니다.

2024-04-09 15:18 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/entity/User.java
> +	String sessionId;
로그인시 생성된 세션 ID가 저장됩니다.

2024-04-09 15:43 UTC, melody-story commented on src/test/java/son/kingofsettlement/user/SingUpTest.java
> +class SignUpTest {
`given전제조건_when동작_then기대결과` 네이밍 컨벤션을 반영해보았습니다.

2024-04-09 16:19 UTC, melody-story commented on build.gradle.kts
> +    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
`spring-boot-starter-test` 패키지 확인결과 junit과 mockito 가 포함되어있는 것을 알게되어 두 라이브러리의 의존성을 제거하였습니다.

2024-04-09 16:20 UTC, melody-story commented on build.gradle.kts
> +    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
`spring-boot-starter-mail`은 모듈의 버전을 제거하여 스프링 부트에서 자체적으로 의존성간 버전 충돌 방지 및 관리하는  `Dependency Versions` 기능 적용토록하였습니다.

2024-04-09 17:54 UTC, melody-story commented on src/main/java/son/kingofsettlement/user/api/SignUpController.java
> +@RequiredArgsConstructor
주석 추가하였습니다.

2024-04-29 16:49 UTC, f-lab-jd commented
리뷰 반영이 완료되어 리뷰가 필요한 상황이라면 다시 말씀 부탁드리겠습니다.

2024-05-13 16:47 UTC, f-lab-jd approved these changes
고생하셨습니다 👍

2024-07-17 06:01 UTC, merged